### ISSUE TITLE
Invalid -f command in docker push

### ISSUE THREAD

**Issue by sowrabhm** [aws-samples/opensource-4g-core-eks#8]
https://github.com/aws-samples/opensource-4g-core-eks/blob/main/Build-Container-Images.md#x86-architecture
contains this command 
```
docker push container_registry/open5gs-x86-aio:41fd851 -f open5gs-epc-aio
```
The `-f` seems to be a flag for the `docker build` command only, and not for `docker push`

**Comment by mgonzalezo** [comment]
I fixed this error by applying the following changes:

Example: container_registry/open5gs-x86-aio image
`
- docker tag container_registry/open5gs-x86-aio:41fd851 [AWS_ID].dkr.ecr.us-east1.amazonaws.com/open5gscore:open5gs-x86-aio
- aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin [AWS_ID].dkr.ecr.us-east-1.amazonaws.com
- docker push [AWS_ID].dkr.ecr.us-east-1.amazonaws.com/open5gscore:open5gs-x86-aio`
